### ISSUE TITLE
ffmpeg non-error text being put out into stderr

### ISSUE THREAD

**Issue by tacohitbox** [alpacamybags118/yt-dlp-exec#7]
Almost all of ffmpeg's output is put into stderr, rather than stdout.

```
[hls @ 0x55f6b946aa40] Skip ('#EXT-X-ALLOW-CACHE:YES')
[hls @ 0x55f6b946aa40] Skip ('#EXT-X-VERSION:5')
Input #0, hls, from '[redacted]':
  Duration: 00:23:55.02, start: 0.101000, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
    Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:/home/[redacted].mp4':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 23.98 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
```

Is there a way to either prevent this for HLS streams?

**Comment by alpacamybags118** [comment]
Hey @tacohitbox thanks for posting! Will take a look and see if I can figure out something

**Comment by alpacamybags118** [comment]
@tacohitbox i finally got a chance to start taking a look at this (sorry for the delay - life stuff). Could you send how you are invoking the code just so I can recreate exactly as you are invoking it. thanks!

**Comment by tacohitbox** [comment]
https://git.gay/a/ytdlp-web/src/branch/main/server.js#L104 here to line 135.

**Comment by alpacamybags118** [comment]
@tacohitbox I spent a bunch of time over the weekend looking into this, and this is what I've found.

First, thanks for sending the code. I set up a sample based off your code and a youtube livestream to recreate the issue. First I decided to see if this was something specific to it being invoked within a node process, so I ran the same command on the terminal using the executables directly and redirected stdout and stderr to files to see what went where

`yt-dlp  https://youtu.be/s3II07bITAI --remux mkv --ffmpeg-location ffmpeg 2>err.log 1>out.log`

What I found was even when executing it via the binary, it was sending the ffmpeg logging to stderr. In addition, when I added a verbose flag to yt-dlp, it was directly verbose logging to stderr as well.

I started digging into their code a bit, and found some of their code related to logging - specifically debug logging.

https://github.com/yt-dlp/yt-dlp/blob/88afe05695464e4242933b9474eaf2b15f8b55bb/yt_dlp/YoutubeDL.py#L932

It seems it will send those logs to either a provider logger's debug logging or if no logger is provided, it just sends them to stderr, which is an interesting choice.

Looking up at the options, I noticed there is an option for `logger` option, but it isnt exposed to the command line interface, but rather its usable if you are invoking this from a python script.

https://github.com/yt-dlp/yt-dlp/blob/88afe05695464e4242933b9474eaf2b15f8b55bb/yt_dlp/YoutubeDL.py#L271

So I decided to make a python script to test this.

```python
from yt_dlp import YoutubeDL

ydl_opts = {
  'remux': 'mkv',
  'ffmpeg-location': 'ffmpeg.exe'
  }
with YoutubeDL(ydl_opts) as ydl:
    ydl.download(['https://youtu.be/s3II07bITAI'])
```

`python .\main.py 1>out.txt 2>err.txt`

Even in the default configuration of the python library, it is also redirecting the ffmpeg output to stderr, so then I decided to make a custom logger to test what I saw in the yt-dlp code regarding a logger

```python
from yt_dlp import YoutubeDL

class TestLogger:
  def debug(self, msg):
    print(f'DEBUG: {msg}');

  def info(self, msg):
    print(f'INFO: {msg}');


  def warning(self, msg):
    print(f'WARNING: {msg}');

  def error(self, msg):
    print(f'ERROR: {msg}');

  def critical(self, msg):
    print(f'CRITICAL: {msg}');

ydl_opts = {
  'remux': 'mkv',
  'ffmpeg-location': 'ffmpeg.exe',
  'logger': TestLogger(),
  }
with YoutubeDL(ydl_opts) as ydl:
    ydl.download(['https://youtu.be/s3II07bITAI'])
```

What came out of this was weird - the ffmpeg logs were not being processed by the logger class at all, none of its logs had the identifier I appended.

I looked more at the library code and found that is not passing any kind of specific stdout or stderr settings to the subprocess, which as far as I understand means it will just share the primary process's handler.

<https://github.com/yt-dlp/yt-dlp/blob/da42679b87005a7a3e08496dc9f5959234e2a8a8/yt_dlp/downloader/external.py#L486>

Lastly, I decided to invoke ffmpeg directly the same way yt-dlp does....and all its logs were also going to stderr.

After all that, I looked a bit more and it turns out....ffmpeg's default behavior is to send all logs to stderr...
<http://ffmpeg.org/ffmpeg.html#toc-Generic-options>

```text
By default the program logs to stderr. If coloring is supported by the terminal, colors are used to mark errors and warnings. Log coloring can be disabled setting the environment variable AV_LOG_FORCE_NOCOLOR, or can be forced setting the environment variable AV_LOG_FORCE_COLOR.
```

From what I've found, the reasoning is that downloaded media can actually be outputted to stdout so they didn't want to mix diagnostic/logging data with that media.

**So to answer your question, there really doesn't seem to be a way to prevent ffmpeg from not writing logs natively to stderr. You could pipe the processes stderr to stdout, or add some logic in a data event of stderr to find the ffmpeg logs and format them as you wish.**

Another option would be to change the yt-dlp lib to allow you to override the ffmpeg subprocess stdout and stderr directing, specifically here <https://github.com/yt-dlp/yt-dlp/blob/da42679b87005a7a3e08496dc9f5959234e2a8a8/yt_dlp/downloader/external.py#L486> . I'm guessing that would mean adding some kind of option for the command line, then adding the logic there to use those settings. I can certainly take a look into adding something like that to their library.

Sorry for the verboseness but wanted to walk through the whole process of elimination. Hopefully this helps explain everything, and sorry I couldn't give you an easy answer! :(

**Comment by tacohitbox** [comment]
No, it's okay. Thank you for trying to help and explaining it to me!
